### ISSUE TITLE
Request: Speak as the GM

### ISSUE THREAD

**Issue by LonePaladin** [cswendrowski/FoundryVTT-Tabbed-Chatlog#13]
Currently, if you are the GM of a game, the only way to speak in the In-Character channel is by selecting a token and "speaking" as that token. This interferes with describing scenes in-game if you are primarily using the chat windows to run the game. Without such an actor, the GM's default mode is OOC, and it also defaults to that if you forget to select the token.

This also plays havoc if you leave the option on to pan the camera whenever someone speaks in-character, since the camera will jump to your invisible actor every time you describe something happening.

I think it would be useful to have an option in this module, to make the GM's default chat entry be considered a scene description and appear as such in the In-Character tab. Require the GM to use the /ooc tag to speak in the OOC channel, just like the players.

**Comment by cswendrowski** [comment]
Tabbed Chat simply reorganizes the existing chat messages, it doesn't modify them. The behavior you are asking for would alter the Type of the GM's chat messages to In Character and probably assign a "speaker" of the current Scene name. This is a fine idea, but doesn't belong in this module. https://github.com/elizeuangelo/fvtt-module-narrator-tools is a promising module for a similar kind of idea - if you ask them to assign narration as In Character type instead of "Other" it would work with Tabbed Chat out of the bat. Otherwise, I'll see if I can whip up a "GM Speak as Scene" module

**Comment by cswendrowski** [comment]
I worked with the author of Narrator tools and Tabbed Chat now integrates with them as of v1.5.0
