### ISSUE TITLE
"Rolls" Tab Too Greedy

### ISSUE THREAD

**Issue by Rinoka** [cswendrowski/FoundryVTT-Tabbed-Chatlog#38]
"Rolls" tab automatically claims /desc, /narrate, and other commands because it greedily takes all system messages. (Narrator Tools is the module I use for these commands.)

I quite literally have to use a workaround to even potentially make it work, when I should really just have the option to merge the Rolls and IC tab.

**Comment by cswendrowski** [comment]
Your issue is written in a way that comes across as fairly rude - please be more thoughtful in the future when logging issues. Tabbed Chatlog, like most opensource projects, is a project of love supported only by snatches of freetime and personal goodwill.

It's not uncommon for modules to conflict in some ways, or interact in ways that might not be considered ideal. Tabbed Chatlog sorts messages marked as "OTHER" into the "Rolls" tab to avoid including them as "In Character" or "Out of Character", a design decision I'm happy with since *most* OTHER rolls are System rolls for things like Actions or Items.

Narrator Tools marks messages as "OTHER" because they aren't any other type of message really - they don't have an "Owning Actor", and so don't default to In-Character. This leads to the behavior you have noticed. It isn't possible for Tabbed Chatlog to sort through the "OTHER" messages - it's not being "greedy" it's just that there isn't *any distinction* between these messages. They are all "OTHER".

Luckily, Narrator Tools actually gives you the option to change the message type it sends! You can configure NT to use the message type that matches the tab you would like the message to appear in. As of the next release of Tabbed Chat, thanks to a pull request by the author of NT, the messages will be defaulted to In Character. You can do this today by running this at world load: `NarratorTools._msgtype = 2`

I hope you continue to enjoy Tabbed Chatlog
